CREATE USER SCOTT IDENTIFIED BY "!Ds1234567890"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- 2) 권한 부여
-- CONNECT 권한              : 접속 권한
-- RESOURCE 권한             : 테이블 등을 사용할 권한
-- CREATE VIEW 권한          : 뷰를 만들 권한
-- UNLIMITED TABLESPACE 권한 : 테이블 생성시 사용할 물리공간 무한으로 사용하는 권한
GRANT CONNECT, RESOURCE, CREATE VIEW TO SCOTT;
GRANT UNLIMITED TABLESPACE TO SCOTT;
